#Wed Jan 22 01:35:09 UTC 2025
micronaut:
  application.name: micronaut-issues
  caches:
    users:
      maximum-size: 100

endpoints:
  caches:
    enabled: true

logger:
  levels:
    io.micronaut.cache: TRACE

datasources:
  default:
    url: jdbc:h2:mem:default
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
