name: build

on:
  push:
    branches:
      - main
      - fix/micronaut-4.6.3

jobs:
  build:

    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Maven build & test
        run: >-
          ./mvnw clean verify
          --no-transfer-progress

